// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVj5GTdS75F2PGcNrGlQ1h0UmZS0oINVk',
    appId: '1:256000945422:web:ace2c28ffc449a9e22fb5f',
    messagingSenderId: '256000945422',
    projectId: 'trainapp-3d67b',
    authDomain: 'trainapp-3d67b.firebaseapp.com',
    storageBucket: 'trainapp-3d67b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzxs4kohR6K3ZFBxiouX9uo_RPgtXAkvw',
    appId: '1:256000945422:android:4843ad77842fca9222fb5f',
    messagingSenderId: '256000945422',
    projectId: 'trainapp-3d67b',
    storageBucket: 'trainapp-3d67b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRTIfaaua8d90785Wkz0Ek01-lSytYmQ',
    appId: '1:256000945422:ios:614b4e6caef3827422fb5f',
    messagingSenderId: '256000945422',
    projectId: 'trainapp-3d67b',
    storageBucket: 'trainapp-3d67b.appspot.com',
    iosBundleId: 'com.example.trainapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYRTIfaaua8d90785Wkz0Ek01-lSytYmQ',
    appId: '1:256000945422:ios:cadc80f34174dee122fb5f',
    messagingSenderId: '256000945422',
    projectId: 'trainapp-3d67b',
    storageBucket: 'trainapp-3d67b.appspot.com',
    iosBundleId: 'com.example.trainapp.RunnerTests',
  );
}
